squash merge of branch github-actions into template im not listing everything in here check the commit history of the github-actions branch

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,6 +44,12 @@ on:
         default: false
         description: Whether or not the result will be a portable application
 
+      package:
+        type: boolean
+        required: true
+        default: false
+        description: Whether or not packaged binaries will be uploaded
+
   workflow_dispatch:
     inputs:
       os:
@@ -86,6 +92,12 @@ on:
         required: true
         default: false
         description: Build portable application
+
+      package:
+        type: boolean
+        required: true
+        default: false
+        description: Build and upload packages
 
 jobs:
   build:
@@ -159,7 +171,7 @@ jobs:
                 ;;
               esac
               cmake_args="$cmake_args -G \"$generator\""
-              case "${{ inputs.os }}" in
+              case "$os" in
                 windows-*) id="win-Ninja" ;;
                 macos-*) id="mac-Ninja" ;;
                 ubuntu-*) id="linux-Ninja" ;;
@@ -221,25 +233,79 @@ jobs:
 
       - uses: actions/checkout@v4
 
+      - name: windows
+        env:
+          REPO_PATH: ${{ github.workspace }}
+        run: |
+          echo "REPO_PATH=$REPO_PATH" >> $GITHUB_ENV
+        shell: bash
+
       - name: Install Latest LLVM on Windows
         if: inputs.compiler == 'clang' && startsWith(inputs.os, 'windows-')
         run: |
-          Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.7/LLVM-20.1.7-win64.exe" -OutFile llvm.exe
-          7z x llvm.exe -o"C:\Program Files\Latest LLVM"
-          echo "C:\Program Files\Latest LLVM\bin" >> $env:GITHUB_PATH
+          curl -Lo llvm.exe "https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.7/LLVM-20.1.7-win64.exe"
+          7z x llvm.exe -o"C:/Program Files/Latest LLVM"
+          echo "C:/Program Files/Latest LLVM/bin" >> $env:GITHUB_PATH
+        shell: bash
 
       - name: Install Linux dependencies
         if: startsWith(inputs.os, 'ubuntu-')
         run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev
+        shell: bash
 
       - name: Configure CMake
-        run: cmake -B ${{ github.workspace }}/build ${{ steps.build-data.outputs.cmake-args }} -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
+        run: |
+          cd $REPO_PATH
+          cmake -S. -Bbuild ${{ steps.build-data.outputs.cmake-args }} -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
+        shell: bash
       - name: Build
-        run: cmake --build ${{ github.workspace }}/build --config ${{ inputs.build-type }}
+        run: |
+          cd $REPO_PATH
+          cmake --build $REPO_PATH/build --config ${{ inputs.build-type }}
+        shell: bash
 
-      - name: Upload
+      - name: Upload Build outputs
         uses: actions/upload-artifact@v4
         if: inputs.upload-outputs
         with:
           name: build-${{ steps.build-data.outputs.id }}-${{ inputs.build-type }}
           path: ${{ github.workspace }}/bin/*
+
+      - name: Install NSIS for Windows
+        if: inputs.package && startsWith(inputs.os, 'windows-')
+        run: |
+          curl -Lo nsis.exe "https://prdownloads.sourceforge.net/nsis/nsis-3.09-setup.exe"
+          7z x nsis.exe -o"C:/Program Files/NSIS"
+          echo "C:/Program Files/NSIS/" >> $GITHUB_PATH
+          "C:/Program Files/NSIS/makensis.exe" -version
+        shell: bash
+
+      - name: Build packages with CPack
+        continue-on-error: true
+        if: inputs.package
+        run: |
+          cd $REPO_PATH
+          mkdir packages
+          cp build/{CPackConfig,CPackSourceConfig}.cmake packages
+          cd packages
+          onFail() {
+            echo;echo;echo;echo "NSIS Log:"
+            cat $REPO_PATH/packages/_CPack_Packages/win64/NSIS/NSISOutput.log || echo "Not found"
+
+            echo;echo;echo;echo "NSIS Script:"
+            cat $REPO_PATH/packages/_CPack_Packages/win64/NSIS/project.nsi || echo "Not found"
+
+            echo;echo;echo;echo "Repo contents:"
+            ls -R "$REPO_PATH"
+          }
+          cpack || onFail
+          rm -rf _CPack_Packages {CPackConfig,CPackSourceConfig}.cmake
+          cd ..
+        shell: bash
+
+      - name: Upload Packages
+        uses: actions/upload-artifact@v4
+        if: inputs.package
+        with:
+          name: packages-${{ inputs.os }}
+          path: ${{ github.workspace }}/packages/*
